use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "options")]
pub enum FieldType {
    Bool,
    String,
    Int,
    Float,
    Color,
    Enum(Vec<std::string::String>),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfigField {
    pub key: std::string::String,
    pub field_type: FieldType,
    pub category: std::string::String,
    pub default: Option<std::string::String>,
    pub description: std::string::String,
}

macro_rules! f {
    ($key:expr, $ft:expr, $cat:expr, $def:expr, $desc:expr) => {
        ConfigField {
            key: $key.into(),
            field_type: $ft,
            category: $cat.into(),
            default: $def,
            description: $desc.into(),
        }
    };
}

macro_rules! fenum {
    ($($v:expr),+) => {
        FieldType::Enum(vec![$($v.into()),+])
    };
}

pub fn get_schema() -> Vec<ConfigField> {
    vec![
        // ── Font ─────────────────────────────────────────────────────────
        f!("font-family", FieldType::String, "font",
            None,
            "主字体族名称，可设置多次以添加回退字体。留空使用系统默认。"),
        f!("font-family-bold", FieldType::String, "font",
            None,
            "粗体字体族。留空则从主字体合成。"),
        f!("font-family-italic", FieldType::String, "font",
            None,
            "斜体字体族。留空则从主字体合成。"),
        f!("font-family-bold-italic", FieldType::String, "font",
            None,
            "粗斜体字体族。留空则从主字体合成。"),
        f!("font-size", FieldType::Float, "font",
            Some("13".into()),
            "字体大小（磅，支持小数），macOS 默认 13，其他平台 12。"),
        f!("font-style", FieldType::String, "font",
            None,
            "命名字体样式（如 Light、Medium），设为 false 则禁用该样式。"),
        f!("font-synthetic-style", FieldType::String, "font",
            Some("true".into()),
            "控制缺失字体样式的合成方式。可选：true、false、no-bold、no-italic、no-bold-italic（逗号分隔）。"),
        f!("font-feature", FieldType::String, "font",
            None,
            "OpenType 字体特性，如 -calt 关闭连字。多个特性逗号分隔。"),
        f!("font-thicken", FieldType::Bool, "font",
            Some("false".into()),
            "加粗字体笔画以提升可读性（仅 macOS）。"),
        f!("font-thicken-strength", FieldType::Int, "font",
            Some("255".into()),
            "font-thicken 启用时的加粗强度（0–255，仅 macOS）。"),
        f!("grapheme-width-method", fenum!("unicode", "legacy"), "font",
            Some("unicode".into()),
            "字符宽度计算方式：unicode（推荐）或 legacy（兼容旧版行为）。"),
        f!("adjust-cell-width", FieldType::String, "font",
            None,
            "单元格宽度调整（像素或百分比，如 1、-2、20%）。"),
        f!("adjust-cell-height", FieldType::String, "font",
            None,
            "单元格高度调整（像素或百分比）。影响光标和 Powerline 字形。"),
        f!("adjust-font-baseline", FieldType::String, "font",
            None,
            "字体基线偏移（从单元格底部，正值向上）。"),
        f!("adjust-underline-position", FieldType::String, "font",
            None,
            "下划线位置调整（从单元格顶部，正值向下）。"),
        f!("adjust-underline-thickness", FieldType::String, "font",
            None,
            "下划线粗细调整。"),
        f!("adjust-strikethrough-position", FieldType::String, "font",
            None,
            "删除线位置调整（从单元格顶部，正值向下）。"),
        f!("adjust-strikethrough-thickness", FieldType::String, "font",
            None,
            "删除线粗细调整。"),
        f!("adjust-cursor-thickness", FieldType::String, "font",
            None,
            "竖线/空心方块光标粗细调整。"),
        f!("adjust-cursor-height", FieldType::String, "font",
            None,
            "光标高度调整（适用于所有光标样式）。"),
        f!("adjust-box-thickness", FieldType::String, "font",
            None,
            "方框绘制字符粗细调整。"),

        // ── Appearance ───────────────────────────────────────────────────
        f!("theme", FieldType::String, "appearance",
            None,
            "配色主题名称、文件路径，或 \"light:主题名,dark:主题名\" 以跟随系统深浅模式。"),
        f!("background", FieldType::Color, "appearance",
            Some("282c34".into()),
            "终端背景色（十六进制 RRGGBB，不含 #）。"),
        f!("foreground", FieldType::Color, "appearance",
            Some("ffffff".into()),
            "终端默认前景色（文本颜色）。"),
        f!("background-opacity", FieldType::Float, "appearance",
            Some("1.0".into()),
            "背景透明度（0.0 完全透明，1.0 完全不透明）。macOS 需重启生效。"),
        f!("background-blur", FieldType::String, "appearance",
            Some("false".into()),
            "背景模糊强度。可选：false、true（=20）、非负整数，或 macos-glass-regular / macos-glass-clear（仅 macOS）。"),
        f!("minimum-contrast", FieldType::Float, "appearance",
            Some("1.0".into()),
            "文字与背景的最低 WCAG 对比度（1.0 不调整，21.0 最大）。"),
        f!("cursor-color", FieldType::Color, "appearance",
            None,
            "光标颜色（十六进制，留空使用前景色）。也可填 cell-foreground 或 cell-background。"),
        f!("cursor-style", fenum!("block", "bar", "underline", "block_hollow"), "appearance",
            Some("block".into()),
            "光标形状：block（方块）、bar（竖线）、underline（下划线）、block_hollow（空心方块）。"),
        f!("cursor-style-blink", fenum!("true", "false"), "appearance",
            None,
            "光标是否闪烁。留空遵循终端 DEC mode 12 设置。"),
        f!("cursor-opacity", FieldType::Float, "appearance",
            Some("1.0".into()),
            "光标不透明度（0.0–1.0）。"),
        f!("cursor-text", FieldType::String, "appearance",
            None,
            "光标下文字颜色，留空使用默认。可填十六进制色值、cell-foreground 或 cell-background。"),
        f!("cursor-click-to-move", FieldType::Bool, "appearance",
            Some("true".into()),
            "在支持 shell integration 的提示符中，允许点击鼠标移动光标。"),
        f!("selection-background", FieldType::Color, "appearance",
            None,
            "选中区域背景色（留空则反色显示）。"),
        f!("selection-foreground", FieldType::Color, "appearance",
            None,
            "选中区域前景色（留空则反色显示）。"),
        f!("selection-clear-on-typing", FieldType::Bool, "appearance",
            Some("true".into()),
            "输入时自动清除选区。"),
        f!("selection-clear-on-copy", FieldType::Bool, "appearance",
            Some("false".into()),
            "复制后自动清除选区。"),
        f!("bold-color", FieldType::String, "appearance",
            None,
            "粗体文字颜色，可填十六进制值或 bright（使用亮色调色板）。"),
        f!("faint-opacity", FieldType::Float, "appearance",
            Some("0.5".into()),
            "淡色文字的不透明度（0.0–1.0）。"),
        f!("alpha-blending", fenum!("native", "linear", "linear-corrected"), "appearance",
            None,
            "Alpha 混合颜色空间：native（平台默认）、linear、linear-corrected。"),
        f!("unfocused-split-opacity", FieldType::Float, "appearance",
            Some("0.7".into()),
            "失焦分屏的不透明度（0.15–1.0）。"),
        f!("split-divider-color", FieldType::Color, "appearance",
            None,
            "分屏分隔线颜色（留空使用默认）。"),

        // ── Background Image ─────────────────────────────────────────────
        f!("background-image", FieldType::String, "appearance",
            None,
            "背景图片路径（PNG/JPEG）。"),
        f!("background-image-opacity", FieldType::Float, "appearance",
            Some("1.0".into()),
            "背景图片相对于 background-opacity 的不透明度。"),
        f!("background-image-position",
            fenum!("center", "top-left", "top-center", "top-right",
                   "center-left", "center-right", "bottom-left",
                   "bottom-center", "bottom-right"),
            "appearance", Some("center".into()),
            "背景图片位置。"),
        f!("background-image-fit",
            fenum!("contain", "cover", "stretch", "none"),
            "appearance", Some("contain".into()),
            "背景图片缩放模式：contain（保持比例留白）、cover（裁剪填满）、stretch（拉伸）、none（原始尺寸）。"),
        f!("background-image-repeat", FieldType::Bool, "appearance",
            Some("false".into()),
            "背景图片平铺重复。"),

        // ── Window ───────────────────────────────────────────────────────
        f!("window-width", FieldType::Int, "window",
            Some("0".into()),
            "初始窗口宽度（字符列数，0 由应用决定，最小 10）。宽高需同时设置。"),
        f!("window-height", FieldType::Int, "window",
            Some("0".into()),
            "初始窗口高度（行数，0 由应用决定，最小 4）。"),
        f!("window-padding-x", FieldType::String, "window",
            Some("2".into()),
            "水平内边距（磅）。可填单值或 \"左,右\" 两值。"),
        f!("window-padding-y", FieldType::String, "window",
            Some("2".into()),
            "垂直内边距（磅）。可填单值或 \"上,下\" 两值。"),
        f!("window-padding-balance",
            fenum!("false", "true", "equal"),
            "window", Some("false".into()),
            "内边距平衡：false 不平衡、true 顶部封顶平衡、equal 完全均匀（需 1.4.0+）。"),
        f!("window-padding-color",
            fenum!("background", "extend", "extend-always"),
            "window", Some("background".into()),
            "内边距区域填充色：background（背景色）、extend（延伸最近单元格色）、extend-always（始终延伸）。"),
        f!("window-decoration",
            fenum!("auto", "none", "client", "server"),
            "window", Some("auto".into()),
            "窗口装饰（标题栏等）：auto、none（无装饰）、client（客户端绘制）、server（服务端绘制）。"),
        f!("window-theme",
            fenum!("auto", "system", "light", "dark", "ghostty"),
            "window", Some("auto".into()),
            "窗口主题：auto（跟随系统）、system、light、dark、ghostty（仅 GTK）。"),
        f!("window-colorspace",
            fenum!("srgb", "display-p3"),
            "window", Some("srgb".into()),
            "终端颜色空间（仅 macOS）：srgb 或 display-p3（广色域）。"),
        f!("window-save-state",
            fenum!("default", "never", "always"),
            "window", Some("default".into()),
            "窗口状态保存与恢复（仅 macOS）。"),
        f!("window-vsync", FieldType::Bool, "window",
            Some("true".into()),
            "渲染与屏幕刷新率同步（仅 macOS）。"),
        f!("window-inherit-working-directory", FieldType::Bool, "window",
            Some("true".into()),
            "新窗口继承当前窗口的工作目录。"),
        f!("window-inherit-font-size", FieldType::Bool, "window",
            Some("true".into()),
            "新窗口/标签页继承当前字体大小。"),
        f!("window-step-resize", FieldType::Bool, "window",
            Some("false".into()),
            "以字符格大小为单位调整窗口尺寸（仅 macOS）。"),
        f!("window-new-tab-position",
            fenum!("current", "end"),
            "window", Some("current".into()),
            "新标签页插入位置：current（当前标签之后）或 end（末尾）。"),
        f!("title", FieldType::String, "window",
            None,
            "强制设置窗口标题（留空则由 shell 动态设置）。"),
        f!("maximize", FieldType::Bool, "window",
            Some("false".into()),
            "启动时最大化窗口。"),
        f!("fullscreen", FieldType::String, "window",
            Some("false".into()),
            "启动时全屏：false、true、non-native（仅 macOS）、non-native-visible-menu。"),
        f!("resize-overlay",
            fenum!("after-first", "always", "never"),
            "window", Some("after-first".into()),
            "调整窗口大小时显示尺寸提示：after-first（首次后显示）、always、never。"),
        f!("resize-overlay-position",
            fenum!("center", "top-left", "top-center", "top-right",
                   "bottom-left", "bottom-center", "bottom-right"),
            "window", Some("center".into()),
            "调整大小提示的显示位置。"),
        f!("resize-overlay-duration", FieldType::String, "window",
            Some("750ms".into()),
            "调整大小提示显示时长（如 500ms、1s）。"),

        // ── Terminal ─────────────────────────────────────────────────────
        f!("command", FieldType::String, "terminal",
            None,
            "启动的 shell 或命令。前缀 direct: 直接执行，shell: 通过 shell 执行。留空使用系统 $SHELL。"),
        f!("working-directory", FieldType::String, "terminal",
            None,
            "初始工作目录。可填绝对路径、~/path、home 或 inherit（继承父进程）。"),
        f!("term", FieldType::String, "terminal",
            Some("xterm-ghostty".into()),
            "TERM 环境变量的值。修改可能影响程序兼容性。"),
        f!("scrollback-limit", FieldType::Int, "terminal",
            Some("10000000".into()),
            "滚动缓冲区大小（字节），默认 10MB。每个终端面板独立计算。"),
        f!("scrollbar",
            fenum!("system", "never"),
            "terminal", Some("system".into()),
            "滚动条显示：system（跟随系统）或 never（始终隐藏）。"),
        f!("shell-integration",
            fenum!("detect", "none", "bash", "elvish", "fish", "nushell", "zsh"),
            "terminal", Some("detect".into()),
            "Shell 集成注入：detect（自动检测）或指定具体 shell 名称。none 禁用。"),
        f!("shell-integration-features", FieldType::String, "terminal",
            None,
            "Shell 集成功能（逗号分隔）：cursor、sudo、title、ssh-env、ssh-terminfo、path。前缀 no- 禁用。"),
        f!("wait-after-command", FieldType::Bool, "terminal",
            Some("false".into()),
            "命令退出后保持终端窗口打开。"),
        f!("link-url", FieldType::Bool, "terminal",
            Some("true".into()),
            "启用 URL 悬停识别与打开。"),
        f!("link-previews",
            fenum!("true", "false", "osc8"),
            "terminal", Some("true".into()),
            "链接预览提示：true（显示）、false（禁用）、osc8（仅 OSC 8 超链接）。"),
        f!("title-report", FieldType::Bool, "terminal",
            Some("false".into()),
            "允许 CSI 21 t 标题上报（用于 tmux 等程序读取窗口标题）。"),
        f!("desktop-notifications", FieldType::Bool, "terminal",
            Some("true".into()),
            "允许终端程序通过 OSC 9/777 发送系统通知。"),
        f!("image-storage-limit", FieldType::Int, "terminal",
            Some("320000000".into()),
            "图片协议（Kitty）图像存储上限（字节），0 表示禁用图片支持。"),
        f!("scroll-to-bottom", FieldType::String, "terminal",
            None,
            "触发滚动到底部的时机（逗号分隔）：keystroke、output。前缀 no- 禁用。"),
        f!("progress-style", FieldType::Bool, "terminal",
            Some("true".into()),
            "支持 ConEmu OSC 9;4 进度条序列。"),

        // ── Mouse ────────────────────────────────────────────────────────
        f!("mouse-hide-while-typing", FieldType::Bool, "mouse",
            Some("false".into()),
            "输入时自动隐藏鼠标光标。"),
        f!("mouse-scroll-multiplier", FieldType::String, "mouse",
            None,
            "滚轮速度倍增。可填数字（如 2.0）或带前缀值（precision:1,discrete:3）。"),
        f!("mouse-shift-capture",
            fenum!("false", "true", "always", "never"),
            "mouse", Some("false".into()),
            "Shift+鼠标行为：false（发送给程序）、true（扩展选区）、always/never 强制覆盖。"),
        f!("mouse-reporting", FieldType::Bool, "mouse",
            Some("true".into()),
            "允许终端程序捕获鼠标事件（如 vim 的鼠标模式）。"),
        f!("focus-follows-mouse", FieldType::Bool, "mouse",
            Some("false".into()),
            "鼠标悬停分屏时自动聚焦。"),
        f!("copy-on-select",
            fenum!("true", "false", "clipboard"),
            "mouse", None,
            "选中文本后自动复制：true（选区剪贴板）、clipboard（系统剪贴板）、false（不复制）。"),
        f!("right-click-action",
            fenum!("context-menu", "paste", "copy", "copy-or-paste", "ignore"),
            "mouse", Some("context-menu".into()),
            "右键行为：弹出菜单、粘贴、复制、智能复制/粘贴，或忽略。"),
        f!("click-repeat-interval", FieldType::Int, "mouse",
            Some("0".into()),
            "双击/三击判定时间间隔（毫秒，0 使用平台默认）。"),

        // ── Clipboard ────────────────────────────────────────────────────
        f!("clipboard-read",
            fenum!("ask", "allow", "deny"),
            "clipboard", Some("ask".into()),
            "OSC 52 剪贴板读取权限：ask（每次询问）、allow（允许）、deny（拒绝）。"),
        f!("clipboard-write",
            fenum!("allow", "ask", "deny"),
            "clipboard", Some("allow".into()),
            "OSC 52 剪贴板写入权限：allow（允许）、ask（每次询问）、deny（拒绝）。"),
        f!("clipboard-trim-trailing-spaces", FieldType::Bool, "clipboard",
            Some("true".into()),
            "复制时去除末尾空白字符。"),
        f!("clipboard-paste-protection", FieldType::Bool, "clipboard",
            Some("true".into()),
            "粘贴看起来危险的内容（如含换行的命令）时弹出确认提示。"),
        f!("clipboard-paste-bracketed-safe", FieldType::Bool, "clipboard",
            Some("true".into()),
            "将括号式粘贴（bracketed paste）视为安全内容，跳过危险确认。"),

        // ── Notifications ────────────────────────────────────────────────
        f!("bell-features", FieldType::String, "misc",
            None,
            "响铃功能（逗号分隔）：system（系统声音）、audio（自定义音频）、attention（任务栏闪烁）、title（标题提示）、border。前缀 no- 禁用。"),
        f!("bell-audio-path", FieldType::String, "misc",
            None,
            "响铃音频文件路径（需配合 bell-features 中的 audio）。"),
        f!("bell-audio-volume", FieldType::Float, "misc",
            Some("0.5".into()),
            "响铃音量（0.0–1.0）。"),

        // ── macOS ────────────────────────────────────────────────────────
        f!("macos-titlebar-style",
            fenum!("transparent", "native", "tabs", "hidden"),
            "macos", Some("transparent".into()),
            "标题栏样式（仅 macOS，仅影响新窗口）：transparent（透明）、native、tabs、hidden（隐藏）。"),
        f!("macos-titlebar-proxy-icon",
            fenum!("visible", "hidden"),
            "macos", Some("visible".into()),
            "标题栏代理图标（仅 native 标题栏下生效）。"),
        f!("macos-window-buttons",
            fenum!("visible", "hidden"),
            "macos", Some("visible".into()),
            "红绿灯关闭/最小化/最大化按钮显示（仅 macOS 1.2.0+）。"),
        f!("macos-option-as-alt",
            fenum!("", "true", "false", "left", "right"),
            "macos", None,
            "将 Option 键视为 Alt：留空自动按键盘布局判断、true、false、left 或 right（仅左/右 Option）。"),
        f!("macos-window-shadow", FieldType::Bool, "macos",
            Some("true".into()),
            "显示 macOS 窗口投影。"),
        f!("macos-auto-secure-input", FieldType::Bool, "macos",
            Some("true".into()),
            "在密码输入提示处自动启用「安全输入」模式，防止键盘记录器。"),
        f!("macos-secure-input-indication", FieldType::Bool, "macos",
            Some("true".into()),
            "安全输入模式激活时显示视觉提示。"),
        f!("macos-hidden",
            fenum!("never", "always"),
            "macos", Some("never".into()),
            "从 Dock 和 App Switcher 隐藏（never / always）。"),
        f!("macos-dock-drop-behavior",
            fenum!("new-tab", "new-window"),
            "macos", Some("new-tab".into()),
            "文件拖拽到 Dock 图标时的行为：在新标签页还是新窗口中打开。"),
        f!("auto-update",
            fenum!("off", "check", "download"),
            "macos", None,
            "自动更新策略（仅 macOS）：off（关闭）、check（仅检查）、download（自动下载）。"),
        f!("auto-update-channel",
            fenum!("stable", "tip"),
            "macos", None,
            "更新渠道（仅 macOS）：stable 或 tip（开发版）。需重启生效。"),

        // ── Misc ─────────────────────────────────────────────────────────
        f!("confirm-close-surface",
            fenum!("true", "false", "always"),
            "misc", Some("true".into()),
            "关闭终端时若有运行中的进程则弹出确认：true（智能判断）、false（不确认）、always（始终确认）。"),
        f!("quit-after-last-window-closed", FieldType::Bool, "misc",
            None,
            "最后一个窗口关闭后退出应用（macOS 默认 false，Linux 默认 true）。"),
        f!("quit-after-last-window-closed-delay", FieldType::String, "misc",
            None,
            "最后窗口关闭后延迟退出时长（如 3s）。最小 1s，仅 Linux。"),
        f!("initial-window", FieldType::Bool, "misc",
            Some("true".into()),
            "应用启动时创建初始窗口。"),
    ]
}
